# Generated by Django 4.2 on 2025-01-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pokemon', models.IntegerField(verbose_name='Id pokemon')),
                ('nombre', models.CharField(default='Sin nombre', max_length=50, verbose_name='Nombre')),
                ('vida', models.IntegerField(default=100, verbose_name='Vida')),
                ('energia', models.DecimalField(decimal_places=4, default=50.0, max_digits=10, verbose_name='Energía')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nivel')),
                ('ivs', models.IntegerField(default=50, verbose_name='Ivs')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('region', models.CharField(default='No definida', max_length=60, verbose_name='Región')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Pokemon',
                'verbose_name_plural': "Pokemon's",
                'ordering': ['id_pokemon'],
            },
        ),
    ]
