# Generated by Django 5.1.5 on 2025-02-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=4, default=50.0, max_digits=10, verbose_name='Temperatura')),
                ('humedad', models.DecimalField(decimal_places=4, default=50.0, max_digits=10, verbose_name='Temperatura')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Sensores',
                'verbose_name_plural': 'Sensores',
                'ordering': ['id'],
            },
        ),
    ]
